id: I8E971E34
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:16:02.471328
last_modified: 2023-02-10 00:16:02.471538
source_metadata:
  title: 'MSV 6,06: Nidāna'
  language: bo
bases:
  AAA6:
    base_file: AAA6.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
